modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Mrbysco/PlayerStatues/issues"
license="MIT"

[[mods]]
modId="player_statues"
version="${file.jarVersion}"
displayName="Player Statues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/player-statues"
authors="Mrbysco, ShyNieke"
description='''
Adds armor stand like entity that render with player skins
'''

[[dependencies.player_statues]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"